[build]
  command = "npm run build -- --configuration production"
  publish = "dist/my-angular-app/browser"

[environment]
  NODE_VERSION = "18"

[[plugins]]
package = "@netlify/angular-runtime"

  [plugins.inputs]
  disabled = true
